import { PDFDocument, StandardFonts, rgb } from "pdf-lib";

function formatNaira(kobo: number) {
  return `NGN ${(kobo / 100).toLocaleString("en-NG")}`;
}

type InvoiceBooking = {
  id: string;
  fullName: string;
  email: string;
  serviceInterest: string;
  agreedAmount: number;
  amountPaid: number;
  payments: { createdAt: Date; provider: string; amount: number }[];
};

export async function generateInvoicePdf(booking: InvoiceBooking): Promise<Uint8Array> {
  const pdfDoc = await PDFDocument.create();
  const page = pdfDoc.addPage([595, 842]); // A4
  const font = await pdfDoc.embedFont(StandardFonts.Helvetica);
  const bold = await pdfDoc.embedFont(StandardFonts.HelveticaBold);

  const brass = rgb(0.894, 0.702, 0.263);
  const ink = rgb(0.05, 0.05, 0.07);
  const slate = rgb(0.45, 0.45, 0.48);

  let y = 780;
  const left = 50;

  page.drawText("NOBS AGENT", { x: left, y, size: 20, font: bold, color: ink });
  y -= 16;
  page.drawText("Kaduna, Nigeria, remote-first, nobsagent0@gmail.com", {
    x: left,
    y,
    size: 9,
    font,
    color: slate,
  });

  y -= 40;
  page.drawText("Invoice", { x: left, y, size: 16, font: bold, color: brass });
  y -= 24;

  page.drawText(`Billed to: ${booking.fullName}`, { x: left, y, size: 11, font, color: ink });
  y -= 16;
  page.drawText(`Email: ${booking.email}`, { x: left, y, size: 11, font, color: ink });
  y -= 16;
  page.drawText(`Project: ${booking.serviceInterest}`, { x: left, y, size: 11, font, color: ink });
  y -= 16;
  page.drawText(`Invoice date: ${new Date().toLocaleDateString("en-NG")}`, {
    x: left,
    y,
    size: 11,
    font,
    color: ink,
  });

  y -= 36;
  page.drawLine({ start: { x: left, y }, end: { x: 545, y }, thickness: 1, color: brass });
  y -= 24;

  page.drawText("Payment history", { x: left, y, size: 13, font: bold, color: ink });
  y -= 22;

  if (booking.payments.length === 0) {
    page.drawText("No payments recorded yet.", { x: left, y, size: 10, font, color: slate });
    y -= 18;
  } else {
    for (const p of booking.payments) {
      page.drawText(new Date(p.createdAt).toLocaleDateString("en-NG"), {
        x: left,
        y,
        size: 10,
        font,
        color: slate,
      });
      page.drawText(p.provider, { x: left + 100, y, size: 10, font, color: slate });
      page.drawText(formatNaira(p.amount), { x: left + 220, y, size: 10, font: bold, color: ink });
      y -= 18;
    }
  }

  y -= 20;
  page.drawLine({ start: { x: left, y }, end: { x: 545, y }, thickness: 0.5, color: slate });
  y -= 24;

  const percentPaid = Math.round((booking.amountPaid / booking.agreedAmount) * 100);
  const remaining = Math.max(0, booking.agreedAmount - booking.amountPaid);

  const summaryRow = (label: string, value: string, highlight = false) => {
    page.drawText(label, { x: left, y, size: 11, font, color: slate });
    page.drawText(value, { x: 350, y, size: 11, font: highlight ? bold : font, color: highlight ? brass : ink });
    y -= 20;
  };

  summaryRow("Total project cost", formatNaira(booking.agreedAmount));
  summaryRow("Total paid to date", `${formatNaira(booking.amountPaid)} (${percentPaid}%)`);
  summaryRow(
    "Remaining balance",
    remaining === 0 ? "Paid in full" : formatNaira(remaining),
    remaining === 0
  );

  y -= 30;
  page.drawText(
    "Generated by NOBS AGENT's client portal. Contact nobsagent0@gmail.com with questions.",
    { x: left, y, size: 8, font, color: slate }
  );

  return pdfDoc.save();
}
